openapi: 3.0.0
info:
  title: "Koa App"
  description: >
    Koa App API.
  version: "1.0.0"
host: "localhost:5000"
schemes:
  - "http"

paths:
  /:
    get:
      summary: "Load home page"
      description: "HTML home page"
      consumes:
        - "application/json"
      produces:
        - "text/html"
      responses:
        200:
      schema:
        type: string
        example: |
          <!DOCTYPE html>
            <html lang="en">
                <head>
                    <meta charset="UTF-8">
                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                    <title>Welcome Page</title>
                    <style>
                        body {
                            font-family: Arial, sans-serif;
                            text-align: center;
                        }
                        h1 {
                            color: #333;
                        }
                    </style>
                </head>
                <body>
                    <h1>Koa App!</h1>
                    <p>make yourself at home</p>
                </body>
            </html>
        500:
          $ref: "#/responses/500"

responses:
  500:
    description: Internal Server Error
    schema:
      $ref: "#/definitions/Error"

definitions:
  Error:
    type: object
    properties:
      message:
        type: string
    required:
      - message
